services:
  api:
    build:
      context: ./docker/api
    container_name: pdg-api
    ports:
      - "8080:80"
    working_dir: /var/www/html
    volumes:
      - ./api/laravel:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: pg-api
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: pdg-detailing.c8z6ucg28z7t.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_DATABASE: pdgdetailing
      DB_USERNAME: codemesh
      DB_PASSWORD: C0d3M3$h100%
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pdg_dash"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
